name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}   
        
    - name: Debug Docker Username
      run: echo "Username is ${{ secrets.DOCKER_USERNAME }}"

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/devops-app:latest 
          ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.sha }}
        platforms: linux/amd64,linux/arm64

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/devops-app:latest

          echo "Pull latest image"
          docker pull $IMAGE

          echo "Run new container on port 8080"
          docker run -d -p 8080:80 --name devops-app-new $IMAGE

          echo "Wait for container to be ready"
          sleep 5

          echo "Stopping old container"
          docker stop devops-app || true
          docker rm devops-app || true

          echo "Switching new container to port 80"
          docker stop devops-app-new
          docker rm devops-app-new
          docker run -d -p 80:80 --name devops-app $IMAGE

          echo "Cleanup"
          docker image prune -f